### ISSUE TITLE
Not compatible with e10s

### ISSUE THREAD

**Issue by rugk** [johnpbloch/De-T-Co#4]
Is this add-on compatible with Electrolysis (e10s)? Electrolysis is the new architecture of Firefox and Mozilla already rolls out some stable Firefox versions with e10s enabled.

More information:
- https://arewee10syet.com/
- https://wiki.mozilla.org/Electrolysis

---

According to [ACL](https://addons.mozilla.org/firefox/addon/add-on-compatibility-reporter/) this add-on is not compatible with e10s.

**Comment by johnpbloch** [comment]
@rugk Thanks for submitting this issue! It's been addressed and will be available on AMO shortly (currently in the review queue).
