### ISSUE TITLE
Breaks list mention links

### ISSUE THREAD

**Issue by rugk** [johnpbloch/De-T-Co#5]
When you receive the "**user** has added you to **user/mylist**" notification the last link (user/mylist) is broken and actually links to `http://@user/mylist`.

**Comment by johnpbloch** [comment]
Thanks for your bug report! I haven't been able to reproduce this error. Can you provide me with a list of steps to take to reproduce the error? My attempts to reproduce the error were:
1. From account A, add account B to a list
2. From account B, go to notifications page
3. See "**A** has added you to **A/list**" notification
4. Click on link to list

The link works as expected from step 4. If you can tell me how to correctly get the error to present itself, I'll be happy to investigate and fix.

**Comment by rugk** [comment]
Yes I think these are the correct STR.
Could you please try to add me to a list (`@rugkme`)?

**Comment by rugk** [comment]
Okay, I think it is another add-on, which caused this: https://github.com/albancrommer/skiptco/issues/9
